### ISSUE TITLE
调用基础扫描报错

### ISSUE THREAD

**Issue by Yellup** [yipianfengye/android-zxingLibrary#11]
环境：MX4  5.1 
调用基础扫描后报错，且界面是一个加号不是四角带滚动条的框？
log:
java.lang.IllegalArgumentException: Both dimensions must be greater than 0
                                                               at com.google.zxing.common.BitMatrix.<init>(BitMatrix.java:50)
                                                               at com.google.zxing.common.GlobalHistogramBinarizer.getBlackMatrix(GlobalHistogramBinarizer.java:91)
                                                               at com.google.zxing.common.HybridBinarizer.getBlackMatrix(HybridBinarizer.java:86)
                                                               at com.google.zxing.BinaryBitmap.getBlackMatrix(BinaryBitmap.java:85)
                                                               at com.google.zxing.qrcode.QRCodeReader.decode(QRCodeReader.java:77)
                                                               at com.google.zxing.MultiFormatReader.decodeInternal(MultiFormatReader.java:171)
                                                               at com.google.zxing.MultiFormatReader.decodeWithState(MultiFormatReader.java:85)
                                                               at com.uuzuche.lib_zxing.decoding.DecodeHandler.decode(DecodeHandler.java:86)
                                                               at com.uuzuche.lib_zxing.decoding.DecodeHandler.handleMessage(DecodeHandler.java:55)
                                                               at android.os.Handler.dispatchMessage(Handler.java:111)
                                                               at android.os.Looper.loop(Looper.java:194)
                                                               at com.uuzuche.lib_zxing.decoding.DecodeThread.run(DecodeThread.java:83)

**Comment by Wang2Mazi** [comment]
把Manifest中的application  的name 属性去掉，试试

**Comment by Yellup** [comment]
谢谢你的回复，但是我有自定义的application应该不能去掉，请问这个问题只能去掉name属性来解决吗？

**Comment by Yellup** [comment]
看了下他的源码，他是在application里做了一些宽高像素的获取，如果有自定义的application，继承他的ZApplication就好了，已解决，非常感谢你提供的方法！

**Comment by Wang2Mazi** [comment]
嗯，也可以把他的源代码作为Module 倒入项目，把屏幕相关的初始化代码，放到我们自定义的application。当然，继承更方便。

**Comment by jsxGitHub** [comment]
nice




------------------ 原始邮件 ------------------
发件人: "Yellup";<notifications@github.com>;
发送时间: 2016年8月30日(星期二) 下午3:22
收件人: "yipianfengye/android-zxingLibrary"<android-zxingLibrary@noreply.github.com>; 

主题: Re: [yipianfengye/android-zxingLibrary] 调用基础扫描报错 (#11)




看了下他的源码，他是在application里做了一些宽高像素的获取，如果有自定义的application，继承他的ZApplication就好了，已解决，非常感谢你提供的方法！

**Comment by chengxianliang** [comment]
其实最简单的不需要继承，直接在自己的Application中添加 ZXingLibrary.initDisplayOpinion(this);就可以了
