### ISSUE TITLE
魅族Flyme调用相机扫一扫异常

### ISSUE THREAD

**Issue by json988** [yipianfengye/android-zxingLibrary#131]
系统Flyme 5.1.11
1.'cn.yipianfengye.android:zxing-library:1.8'版本在魅族上调用相机被拒绝权限后会崩溃
java.lang.NullPointerException: Attempt to read from field 'int android.graphics.Point.x' on a null object reference
at com.uuzuche.lib_zxing.camera.CameraManager.getFramingRect(CameraManager.java:230)

2.在2.2版本上表现为拒绝后显示黑屏可返回

**Comment by piitw** [comment]
同样的问题

**Comment by CodeXiaoMai** [comment]
我也遇到了同样的问题，魅族上架审核没有通过
`[{"brandName":"魅族","failMsg":"// CRASH: 我的包名 (pid 22724)\n// Short Msg: java.lang.NullPointerException\n// Long Msg: java.lang.NullPointerException: Attempt to read from field 'int android.graphics.Point.x' on a null object reference (clone 0)\n// Build Label: Meizu/M1621/M1621:6.0/MRA58K/1495809194:user/release-keys\n// Build Changelist: 1495809194\n// Build Time: 1495809607000\n// java.lang.NullPointerException: Attempt to read from field 'int android.graphics.Point.x' on a null object reference\n// \tat com.uuzuche.lib_zxing.camera.CameraManager.e(Unknown Source)\n// \tat com.uuzuche.lib_zxing.view.ViewfinderView.onDraw(Unknown Source)\n// \tat android.view.View.draw(View.java:16532)\n// \tat android.view.View.updateDisplayListIfDirty(View.java:15485)\n// \tat android.view.View.draw(View.java:16286)\n// \tat android.view.ViewGroup.drawChild(ViewGroup.java:3735)\n// \tat android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)\n// \tat android.view.View.updateDisplayListIfDirty(View.java:15477)\n// \tat android.view.View.draw(View.java:16286)\n// \tat android.view.ViewGroup.drawChild(ViewGroup.java:3735)\n// \tat android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)\n// \tat android.view.View.updateDisplayListIfDirty(View.java:15477)\n// \tat android.view.View.draw(View.java:16286)\n// \tat android.view.ViewGroup.drawChild(ViewGroup.java:3735)\n// \tat android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)\n// \tat android.view.View.updateDisplayListIfDirty(View.java:15477)\n// \tat android.view.View.draw(View.java:16286)\n// \tat android.view.ViewGroup.drawChild(ViewGroup.java:3735)\n// \tat android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)\n// \tat android.view.View.updateDisplayListIfDirty(View.java:15477)\n// \tat android.view.View.draw(View.java:16286)\n// \tat android.view.ViewGroup.drawChild(ViewGroup.java:3735)\n// \tat android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)\n// \tat android.view.View.updateDisplayListIfDirty(View.java:15477)\n// \tat android.view.View.draw(View.java:16286)\n// \tat android.view.ViewGroup.drawChild(ViewGroup.java:3735)\n// \tat android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)\n// \tat android.view.View.updateDisplayListIfDirty(View.java:15477)\n// \tat android.view.View.draw(View.java:16286)\n// \tat android.view.ViewGroup.drawChild(ViewGroup.java:3735)\n// \tat android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)\n// \tat android.view.View.updateDisplayListIfDirty(View.java:15477)\n// \tat android.view.View.draw(View.java:16286)\n// \tat android.view.ViewGroup.drawChild(ViewGroup.java:3735)\n// \tat android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)\n// \tat com.android.internal.policy.PhoneWindow$DecorView.dispatchDraw(PhoneWindow.java:2825)\n// \tat android.view.View.draw(View.java:16544)\n// \tat com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2806)\n// \tat android.view.View.updateDisplayListIfDirty(View.java:15485)\n// \tat android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:286)\n// \tat android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:292)\n// \tat android.view.ThreadedRenderer.draw(ThreadedRenderer.java:327)\n// \tat android.view.ViewRootImpl.draw(ViewRootImpl.java:3041)\n// \tat android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2845)\n// \tat android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2454)\n// \tat android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1340)\n// \tat android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6809)\n// \tat android.view.Choreographer$CallbackRecord.run(Choreographer.java:894)\n// \tat android.view.Choreographer.doCallbacks(Choreographer.java:696)\n// \tat android.view.Choreographer.doFrame(Choreographer.java:631)\n// \tat android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:880)\n// \tat android.os.Handler.handleCallback(Handler.java:815)\n// \tat android.os.Handler.dispatchMessage(Handler.java:104)\n// \tat android.os.Looper.loop(Looper.java:207)\n// \tat android.app.ActivityThread.main(ActivityThread.java:5933)\n// \tat java.lang.reflect.Method.invoke(Native Method)\n// \tat com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:958)\n// \tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:819)\n// \n","modelName":"魅蓝 Note5","osVersion":"2.2.4"}]`

**Comment by CodeXiaoMai** [comment]
我升级到 2.2 版本后，这个问题应该是已经解决了

**Comment by lylylywww** [comment]
Unexpected error initializing camera
                                                                java.lang.RuntimeException: Method called after release()
                                                                    at android.hardware.Camera.setPreviewSurface(Native Method)
                                                                    at android.hardware.Camera.setPreviewDisplay(Camera.java:661)
                                                                    at com.dtr.zxing.camera.CameraManager.openDriver(CameraManager.java:87)
                                                                    at com.dtr.zxing.activity.CaptureActivity.initCamera(CaptureActivity.java:206)
                                                                    at com.dtr.zxing.activity.CaptureActivity.surfaceCreated(CaptureActivity.java:162)
现在还是崩溃，用的时你最新的代码2017-09-14日下载的，还是魅族手机5.1的系统点拒绝（打开摄像头时）还是崩溃，报错如上

**Comment by lovejjfg** [comment]
最好直接拷贝代码改，或者在跳转之前就进行授权确认。

**Comment by lylylywww** [comment]
解决了，在你代码抓取异常的地方处理了





------------------ 原始邮件 ------------------
发件人: "Joe";<notifications@github.com>;
发送时间: 2017年9月30日(星期六) 晚上6:03
收件人: "yipianfengye/android-zxingLibrary"<android-zxingLibrary@noreply.github.com>;
抄送: "danel"<57457243@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [yipianfengye/android-zxingLibrary] 魅族Flyme调用相机扫一扫异常 (#131)




最好直接拷贝代码改，或者在跳转之前就进行授权确认。
