### ISSUE TITLE
扫描二维码闪退

### ISSUE THREAD

**Issue by JsonWong87** [yipianfengye/android-zxingLibrary#190]
java.lang.RuntimeException: Camera is being used after Camera.release() was called
                                                                        at android.hardware.Camera._stopPreview(Native Method)
                                                                        at android.hardware.Camera.stopPreview(Camera.java:730)
                                                                        at com.uuzuche.lib_zxing.activity.CaptureFragment.surfaceDestroyed(CaptureFragment.java:186)
                                                                        at android.view.SurfaceView.updateWindow(SurfaceView.java:567)
                                                                        at android.view.SurfaceView.onWindowVisibilityChanged(SurfaceView.java:239)
                                                                        at android.view.View.dispatchWindowVisibilityChanged(View.java:9647)
                                                                        at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1309)
                                                                        at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1309)
                                                                        at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1309)
                                                                        at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1309)
                                                                        at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1309)
                                                                        at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1309)
                                                                        at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1309)
                                                                        at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1309)
                                                                        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1383)
                                                                        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
                                                                        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
                                                                        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                        at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                        at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:148)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by huyaoqing1995** [comment]
How to reslove this problem
