### ISSUE TITLE
Camera is being used after Camera.release() was called

### ISSUE THREAD

**Issue by appsming** [yipianfengye/android-zxingLibrary#239]
Process: com.kyexpress.platenumberdemo, PID: 15045
    java.lang.RuntimeException: Camera is being used after Camera.release() was called
        at android.hardware.Camera._stopPreview(Native Method)
        at android.hardware.Camera.stopPreview(Camera.java:813)
        at com.kyexpress.kyscaner.activity.CaptureFragment.surfaceDestroyed(CaptureFragment.java:185)
        at android.view.SurfaceView.updateWindow(SurfaceView.java:622)
        at android.view.SurfaceView.onWindowVisibilityChanged(SurfaceView.java:264)
        at android.view.View.dispatchWindowVisibilityChanged(View.java:10347)
        at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1289)
        at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1289)
        at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1289)
        at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1289)
        at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1289)
        at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1289)
        at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1289)
        at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1289)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1674)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1372)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6782)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:933)
        at android.view.Choreographer.doCallbacks(Choreographer.java:742)
        at android.view.Choreographer.doFrame(Choreographer.java:674)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:919)
        at android.os.Handler.handleCallback(Handler.java:761)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6623)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by licoba** [comment]
是因为自定义CustomViewfinderView了吗？

**Comment by zaxcler** [comment]
这个问题解决了嘛，我也遇到这个问题了

**Comment by 1Patience-and-1careful** [comment]
同样遇到了

**Comment by Sola1** [comment]
扫描成功后想再次打开扫描页面就会报这个错
