### ISSUE TITLE
扫一扫崩溃了

### ISSUE THREAD

**Issue by FrameJack** [yipianfengye/android-zxingLibrary#43]
1.9版本的
下面是错误码：

 java.lang.IllegalArgumentException: Both dimensions must be greater than 0
                                                                    at com.google.zxing.common.BitMatrix.<init>(BitMatrix.java:50)
                                                                    at com.google.zxing.common.GlobalHistogramBinarizer.getBlackMatrix(GlobalHistogramBinarizer.java:91)
                                                                    at com.google.zxing.common.HybridBinarizer.getBlackMatrix(HybridBinarizer.java:86)
                                                                    at com.google.zxing.BinaryBitmap.getBlackMatrix(BinaryBitmap.java:85)
                                                                    at com.google.zxing.qrcode.QRCodeReader.decode(QRCodeReader.java:77)
                                                                    at com.google.zxing.MultiFormatReader.decodeInternal(MultiFormatReader.java:171)
                                                                    at com.google.zxing.MultiFormatReader.decodeWithState(MultiFormatReader.java:85)
                                                                    at com.uuzuche.lib_zxing.decoding.DecodeHandler.decode(DecodeHandler.java:86)
                                                                    at com.uuzuche.lib_zxing.decoding.DecodeHandler.handleMessage(DecodeHandler.java:55)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                    at android.os.Looper.loop(Looper.java:145)
                                                                    at com.uuzuche.lib_zxing.decoding.DecodeThread.run(DecodeThread.java:83)

**Comment by panhongzhi02** [comment]
2.0 版本我也遇到了，求解决方案

**Comment by panhongzhi02** [comment]
sorry，忘了替换新写的Application了

**Comment by yipianfengye** [comment]
需要添加新的Application
