### ISSUE TITLE
onActivityResult()回调中崩溃(Nexus 6-api24)

### ISSUE THREAD

**Issue by xiong-it** [yipianfengye/android-zxingLibrary#48]
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: cn.hongjitech.onroad, PID: 2334
                                                                    java.lang.RuntimeException: Camera is being used after Camera.release() was called
                                                                        at android.hardware.Camera._stopPreview(Native Method)
                                                                        at android.hardware.Camera.stopPreview(Camera.java:730)
                                                                        at com.uuzuche.lib_zxing.activity.CaptureFragment.surfaceDestroyed(CaptureFragment.java:183)
                                                                        at android.view.SurfaceView.updateWindow(SurfaceView.java:592)
                                                                        at android.view.SurfaceView.onWindowVisibilityChanged(SurfaceView.java:251)
                                                                        at android.view.View.dispatchWindowVisibilityChanged(View.java:10276)
                                                                        at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1289)
                                                                        at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1289)
                                                                        at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1289)
                                                                        at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1289)
                                                                        at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1289)
                                                                        at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1289)
                                                                        at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1289)
                                                                        at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1289)
                                                                        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1534)
                                                                        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1246)
                                                                        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6301)
                                                                        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
                                                                        at android.view.Choreographer.doCallbacks(Choreographer.java:683)
                                                                        at android.view.Choreographer.doFrame(Choreographer.java:619)
                                                                        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
                                                                        at android.os.Handler.handleCallback(Handler.java:751)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by xiong-it** [comment]
将CameraManager.get().closeDriver();从Fragment的onPause中移至onDestroy中即可。
