### ISSUE TITLE
权限改为询问后，再次进入定制化扫描崩溃

### ISSUE THREAD

**Issue by hulegithub** [yipianfengye/android-zxingLibrary#51]
请问这个问题怎么解决，谢谢！这个bug一直存在，是必现的
                                               Process: com.uuch.android_zxinglibrary, PID: 4621
                                                 java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=101, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.uuch.android_zxinglibrary/com.uuch.android_zxinglibrary.MainActivity}: java.lang.RuntimeException: Cannot execute non-void method cameraTask
                                                     at android.app.ActivityThread.deliverResults(ActivityThread.java:3706)
                                                     at android.app.ActivityThread.handleSendResult(ActivityThread.java:3749)
                                                     at android.app.ActivityThread.access$1400(ActivityThread.java:153)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1400)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5438)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
                                                  Caused by: java.lang.RuntimeException: Cannot execute non-void method cameraTask
                                                     at pub.devrel.easypermissions.EasyPermissions.runAnnotatedMethods(EasyPermissions.java:297)
                                                     at pub.devrel.easypermissions.EasyPermissions.onRequestPermissionsResult(EasyPermissions.java:241)
                                                     at com.uuch.android_zxinglibrary.MainActivity.onRequestPermissionsResult(MainActivity.java:143)
                                                     at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:6634)
                                                     at android.app.Activity.dispatchActivityResult(Activity.java:6512)
                                                     at android.app.ActivityThread.deliverResults(ActivityThread.java:3702)
                                                     at android.app.ActivityThread.handleSendResult(ActivityThread.java:3749) 
                                                     at android.app.ActivityThread.access$1400(ActivityThread.java:153) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1400) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:148) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5438) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

**Comment by hulegithub** [comment]
我已经解决，是授权的时候方法不能带参数

**Comment by JefferyLeng** [comment]
在第一次弹出Permission check的时候，选择允许,会重现该bug,选择之后，第二次进入 是没有问题的

**Comment by Faaants** [comment]
@hulegithub 怎么解决的？？？

**Comment by hulegithub** [comment]
@Faaants   授权的时候方法不能带参数,如下：
  @AfterPermissionGranted(REQUEST_CAMERA_PERM)
    public void cameraTask(int viewId) {     //此处不要带参数viewId
        if (EasyPermissions.hasPermissions(this, Manifest.permission.CAMERA)) {
            // Have permission, do the thing!
            onClick(viewId);
        } else {
            // Ask for one permission
            EasyPermissions.requestPermissions(this, "需要请求camera权限",
                    REQUEST_CAMERA_PERM, Manifest.permission.CAMERA);
        }
    }
