### ISSUE TITLE
打开CaptureActivity之后闪退

### ISSUE THREAD

**Issue by wangran99** [yipianfengye/android-zxingLibrary#62]
日志显示：
                                                                        Process: com.lianfan.testcamera, PID: 17855
                                                                        java.lang.IllegalArgumentException: Both dimensions must be greater than 0
                                                                            at com.google.zxing.common.BitMatrix.<init>(BitMatrix.java:50)
                                                                            at com.google.zxing.common.GlobalHistogramBinarizer.getBlackMatrix(GlobalHistogramBinarizer.java:91)
                                                                            at com.google.zxing.common.HybridBinarizer.getBlackMatrix(HybridBinarizer.java:86)
                                                                            at com.google.zxing.BinaryBitmap.getBlackMatrix(BinaryBitmap.java:85)
                                                                            at com.google.zxing.qrcode.QRCodeReader.decode(QRCodeReader.java:77)
                                                                            at com.google.zxing.MultiFormatReader.decodeInternal(MultiFormatReader.java:171)
                                                                            at com.google.zxing.MultiFormatReader.decodeWithState(MultiFormatReader.java:85)
                                                                            at com.uuzuche.lib_zxing.decoding.DecodeHandler.decode(DecodeHandler.java:86)
                                                                            at com.uuzuche.lib_zxing.decoding.DecodeHandler.handleMessage(DecodeHandler.java:55)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:135)
                                                                            at com.uuzuche.lib_zxing.decoding.DecodeThread.run(DecodeThread.java:83)

**Comment by Hellozhongxin** [comment]
我也遇到这个问题，请问如何解决？

**Comment by JohnsonHou** [comment]
@wangran99 解决了吗

**Comment by itzihao** [comment]
同上+1
