### ISSUE TITLE
魅族的手机，拒绝权限之后，报空指针异常

### ISSUE THREAD

**Issue by yiyudemei** [yipianfengye/android-zxingLibrary#71]
java.lang.NullPointerException: Attempt to read from field 'int android.graphics.Point.x' on a null object reference
	at com.uuzuche.lib_zxing.camera.CameraManager.getFramingRect(CameraManager.java:230)
	at com.uuzuche.lib_zxing.view.ViewfinderView.onDraw(ViewfinderView.java:119)
	at android.view.View.draw(View.java:15615)
	at android.view.View.updateDisplayListIfDirty(View.java:14504)
	at android.view.View.getDisplayList(View.java:14533)
	at android.view.View.draw(View.java:15324)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3536)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3329)
	at android.view.View.updateDisplayListIfDirty(View.java:14496)
	at android.view.View.getDisplayList(View.java:14533)
	at android.view.View.draw(View.java:15324)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3536)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3329)
	at android.view.View.updateDisplayListIfDirty(View.java:14496)
	at android.view.View.getDisplayList(View.java:14533)
	at android.view.View.draw(View.java:15324)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3536)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3329)
	at android.view.View.updateDisplayListIfDirty(View.java:14496)
	at android.view.View.getDisplayList(View.java:14533)
	at android.view.View.draw(View.java:15324)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3536)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3329)
	at android.view.View.draw(View.java:15627)
	at android.widget.FrameLayout.draw(FrameLayout.java:658)
	at android.view.View.updateDisplayListIfDirty(View.java:14504)
	at android.view.View.getDisplayList(View.java:14533)
	at android.view.View.draw(View.java:15324)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3536)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3329)
	at android.view.View.updateDisplayListIfDirty(View.java:14496)
	at android.view.View.getDisplayList(View.java:14533)
	at android.view.View.draw(View.java:15324)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3536)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3329)
	at android.view.View.updateDisplayListIfDirty(View.java:14496)
	at android.view.View.getDisplayList(View.java:14533)
	at android.view.View.draw(View.java:15324)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3536)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3329)
	at android.view.View.updateDisplayListIfDirty(View.java:14496)
	at android.view.View.getDisplayList(View.java:14533)
	at android.view.View.draw(View.java:15324)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3536)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3329)
	at android.view.View.updateDisplayListIfDirty(View.java:14496)
	at android.view.View.getDisplayList(View.java:14533)
	at android.view.View.draw(View.java:15324)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3536)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3329)
	at android.view.View.updateDisplayListIfDirty(View.java:14496)
	at android.view.View.getDisplayList(View.java:14533)
	at android.view.View.draw(View.java:15324)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3536)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3329)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchDraw(PhoneWindow.java:2845)
	at android.view.View.draw(View.java:15627)
	at android.widget.FrameLayout.draw(FrameLayout.java:658)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2820)
	at android.view.View.updateDisplayListIfDirty(View.java:14504)
	at android.view.View.getDisplayList(View.java:14533)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:279)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:285)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:335)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2987)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2801)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2412)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1320)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6733)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:800)
	at android.view.Choreographer.doCallbacks(Choreographer.java:603)
	at android.view.Choreographer.doFrame(Choreographer.java:572)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:786)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5869)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1019)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:814)

**Comment by S-Co** [comment]
同错求助 @yiyudemei
