### ISSUE TITLE
这种异常 是怎么导致的？可能是我没有finish 这个页面 ？

### ISSUE THREAD

**Issue by thisfeng** [yipianfengye/android-zxingLibrary#81]
java.lang.RuntimeException: startPreview failed
                                                                                 at android.hardware.Camera.startPreview(Native Method)
                                                                                 at com.uuzuche.lib_zxing.camera.CameraManager.startPreview(CameraManager.java:163)
                                                                                 at com.uuzuche.lib_zxing.decoding.CaptureActivityHandler.<init>(CaptureActivityHandler.java:64)
                                                                                 at com.uuzuche.lib_zxing.activity.CaptureFragment.initCamera(CaptureFragment.java:156)
                                                                                 at com.uuzuche.lib_zxing.activity.CaptureFragment.surfaceCreated(CaptureFragment.java:170)
                                                                                 at android.view.SurfaceView.updateWindow(SurfaceView.java:602)
                                                                                 at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:184)
                                                                                 at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
                                                                                 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2184)
                                                                                 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1205)
                                                                                 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6318)
                                                                                 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:862)
                                                                                 at android.view.Choreographer.doCallbacks(Choreographer.java:674)
                                                                                 at android.view.Choreographer.doFrame(Choreographer.java:610)
                                                                                 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:848)
                                                                                 at android.os.Handler.handleCallback(Handler.java:739)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                 at android.os.Looper.loop(Looper.java:179)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5672)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)

**Comment by thisfeng** [comment]
http://blog.csdn.net/davidbeckham2901/article/details/7696497  
一般Camera调用open以及startPreview需要确保不多次调用，
我的上面的操作 导致的
