### ISSUE TITLE
报错了 'int android.graphics.Point.x' on a null object reference

### ISSUE THREAD

**Issue by toothwind** [yipianfengye/android-zxingLibrary#96]
at com.uuzuche.lib_zxing.camera.CameraManager.getFramingRect(CameraManager.java:230)
	at com.uuzuche.lib_zxing.view.ViewfinderView.onDraw(ViewfinderView.java:119)

**Comment by qujc** [comment]
i got the same issue, on Meizu Pro6s based on Android 6.0 & Flyme 5.2.6.2A, @yipianfengye help me~

**Comment by lvzhihao100** [comment]
我的也出现了这种问题，用户拒绝照相权限后，会出现这种情况，android 5.0 魅族pro4

**Comment by qujc** [comment]
i found that caused by camera.setPreviewDisplay(holder) method in CameraManager.class at line 124, the exception info was "Camera is being used after Camera.release() was called". But why ?

**Comment by toothwind** [comment]
deny camera-permission caused.

**Comment by lnkywd** [comment]
在 camera = Camera.open(); 这里加入try catch，因为魅族拒绝相机权限时 Camera.open() 返回的不是 null ，主动设置一下 camera = null 就好。
